### ISSUE TITLE
Hi, I tested but it didn't work (demo code included)

### ISSUE THREAD

**Issue by 1c7** [soffes/HotKey#13]
## Screenshot
![image](https://user-images.githubusercontent.com/1804755/57965223-02b38f00-7974-11e9-9361-0819c62b47ab.png)

**Hi soffes**,
Thanks for open source this repo.

I tested it with a demo project but it didn't work.
Would you mind check it out?

Code: https://github.com/1c7/testHotKey

**Comment by soffes** [comment]
Thanks for such a thorough issue! I'm not sure offhand. Let me know if you figure it out!

**Comment by 1c7** [comment]
Oh I discontinue my macOS Swift project. I guess I should close this now
