### ISSUE TITLE
Doesn't seem to work?

### ISSUE THREAD

**Issue by ospfranco** [soffes/HotKey#26]
Hey, first thanks for creating the library, I was just in the process of setting it up, so I'm just doing some basic test, but this doesn't seem to work:

```swift
func applicationDidFinishLaunching(_ aNotification: Notification) {
       // Register global hotkey
        let hotkey = HotKey(keyCombo: KeyCombo(key: .r, modifiers: [.command, .option]))
        hotkey.keyDownHandler = {
            print("Something should happen")
        }
```

Am I registering it the wrong place or?

**Comment by ospfranco** [comment]
Ah, I just got it working, the hotkey declaration cannot be a local variable, it needs to be in the class so it doesn't get de-allocated, I think it would be useful to mention it on the Readme, I will create a PR

**Comment by ospfranco** [comment]
https://github.com/soffes/HotKey/pull/27

**Comment by wilbertliu** [comment]
Thank you so much @ospfranco, it's truly helpful! 🙏🏻

**Comment by bb-04** [comment]
thanks I needed this! needs to be added to readme

**Comment by lx70770** [comment]
thanks

**Comment by LingYanSi** [comment]
thanks
