### ISSUE TITLE
Apple Silicon

### ISSUE THREAD

**Issue by cdf1982** [soffes/HotKey#34]
Hi!
I've been thinking of adding a global shortcut to a Mac app, but I also plan to soon natively support Apple Silicon.
**My question: HotKey wraps the Carbon APIs, is that still possible on M1?**
My guess is not, but my research online only confirmed that Carbon audio APIs are gone, which makes me think that all Carbon is, but does not confirm it 100%.
**Second question: if Carbon is gone with Apple Silicon, have you found other ways to have global shortcuts?**
Thank you for the project and for your time!

**Comment by oliverepper** [comment]
I just tried adding a shortcut to a native M1 app. Works perfectly.

**Comment by cdf1982** [comment]
Thank you for testing this, it’s great news! I would have tried to do that, but the DTK is on its way and I’m keeping my fingers crossed for June before pulling the trigger on new hardware.

Thanks again!
